# Settings for ros_control control loop
hardware_control_loop:
   loop_hz: 125

# Settings for ros_control hardware interface
hardware_interface:
   joints:
     - ur3_joint_1
     - ur3_joint_2
     - ur3_joint_3
     - ur3_joint_4
     - ur3_joint_5
     - ur3_joint_6

# Publish all joint states ----------------------------------
joint_state_controller:
   type:         joint_state_controller/JointStateController
   publish_rate: 125

# Publish wrench ----------------------------------
force_torque_sensor_controller:
   type:         force_torque_sensor_controller/ForceTorqueSensorController
   publish_rate: 125

# Joint Trajectory Controller - position based -------------------------------
# For detailed explanations of parameter see http://wiki.ros.org/joint_trajectory_controller
pos_based_pos_traj_controller:
   type: position_controllers/JointTrajectoryController
   joints:
     - ur3_joint_1
     - ur3_joint_2
     - ur3_joint_3
     - ur3_joint_4
     - ur3_joint_5
     - ur3_joint_6
   constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      ur3_joint_1: {trajectory: 0.1, goal: 0.1}
      ur3_joint_2: {trajectory: 0.1, goal: 0.1}
      ur3_joint_3: {trajectory: 0.1, goal: 0.1}
      ur3_joint_4: {trajectory: 0.1, goal: 0.1}
      ur3_joint_5: {trajectory: 0.1, goal: 0.1}
      ur3_joint_6: {trajectory: 0.1, goal: 0.1}
   stop_trajectory_duration: 0.5
   state_publish_rate:  125
   action_monitor_rate: 10

   # state_publish_rate:  50 # Defaults to 50
   # action_monitor_rate: 20 # Defaults to 20
   #stop_trajectory_duration: 0 # Defaults to 0.0

# Joint Trajectory Controller - velocity based -------------------------------
# For detailed explanations of parameter see http://wiki.ros.org/joint_trajectory_controller
vel_based_pos_traj_controller:
   type: velocity_controllers/JointTrajectoryController
   joints:
     - ur3_joint_1
     - ur3_joint_2
     - ur3_joint_3
     - ur3_joint_4
     - ur3_joint_5
     - ur3_joint_6
   constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      ur3_joint_1: {trajectory: 0.1, goal: 0.1}
      ur3_joint_2: {trajectory: 0.1, goal: 0.1}
      ur3_joint_3: {trajectory: 0.1, goal: 0.1}
      ur3_joint_4: {trajectory: 0.1, goal: 0.1}
      ur3_joint_5: {trajectory: 0.1, goal: 0.1}
      ur3_joint_6: {trajectory: 0.1, goal: 0.1}
   stop_trajectory_duration: 0.5
   state_publish_rate:  125
   action_monitor_rate: 10
   gains:
      #!!These values have not been optimized!!
      ur3_joint_1:  {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
      ur3_joint_2: {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
      ur3_joint_3:         {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
      ur3_joint_4:       {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
      ur3_joint_5:       {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
      ur3_joint_6:       {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}

   # Use a feedforward term to reduce the size of PID gains
   velocity_ff:
    ur3_joint_1: 1.0
    ur3_joint_2: 1.0
    ur3_joint_3: 1.0
    ur3_joint_4: 1.0
    ur3_joint_5: 1.0
    ur3_joint_6: 1.0

   # state_publish_rate:  50 # Defaults to 50
   # action_monitor_rate: 20 # Defaults to 20
   #stop_trajectory_duration: 0 # Defaults to 0.0

# Pass an array of joint velocities directly to the joints
joint_group_vel_controller:
   type: velocity_controllers/JointGroupVelocityController
   joints:
     - ur3_joint_1
     - ur3_joint_2
     - ur3_joint_3
     - ur3_joint_4
     - ur3_joint_5
     - ur3_joint_6
